name: Linter

on: [push, pull_request]

jobs:
  superlinter:
    name: Super Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          # Don't check already existent files
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_GITHUB_ACTIONS: false
          LINTER_RULES_PATH: /.github/workflows/
          MARKDOWN_CONFIG_FILE: config/config.json
          MARKDOWN_CUSTOM_RULE_GLOBS: rules/rules.js
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
